### ISSUE TITLE
Add Portal and Portlet states

### ISSUE THREAD

**Issue by madki** [workarounds/portal#1]
Add states of Portal and Portlets to Shared Preferences. Provide static methods for easy access. 
Find a ways to enable adding a listener without the library users having to know the exact keys of the states.

**Comment by okmanideep** [comment]
@madki  Now that we have `getPortal()`, is this necessary?

**Comment by madki** [comment]
Yeah this is not needed anymore. And adding them to SharedPreferences was a bad idea anyway. Every component that has a reference to the `PortalAdapter` or `PortalService` can get the portal. Other components like activities or fragments that don't have a handle to either can bind to the service.
